[package]
name = "scout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.19.5"
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_12"] }
