import { Button, VerticalBox, ScrollView, ListView } from "std-widgets.slint";

export component FlatFileTree {
    in property <[string]> files;
}

export enum SolItemType {
    Folder,
    File,
    Script,
    Eml,
}

export struct SolItem {
    name: string,
    item_type: SolItemType,
    active: bool,
    selected: bool,
    index: int,
    path: string,
}

export component AppWindow inherits Window {
    in property <[SolItem]> files;
    in property <[SolItem]> child_files;
    in property <string> content_of_file;
    callback set-active-folder(string);
    callback key_presed(string);

    width: 1000px;
    height: 500px;

    background: #383C4A;
    FocusScope {
        key-pressed(event) => {
            key_presed(event.text);
            accept
        }
    }

    GridLayout {
        ScrollView {
            width: parent.width / 3;
            height: parent.height;
            viewport-height: parent.height;

            ListView {
                for data in files: Rectangle {
                    GridLayout {
                        Row {
                            Rectangle {
                                background: #3B4052;

                                TouchArea {

                                    Text {
                                        text: data.name;
                                    }

                                    clicked => {
                                        set-active-folder(data.name)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        ScrollView {
            width: parent.width / 3;
            height: parent.height;
            viewport-width: parent.width / 3;
            viewport-height: parent.height;

            ListView {
                for data in child_files: Rectangle {
                    GridLayout {
                        Row {
                            Rectangle {
                                background: #3B4052;

                                TouchArea {

                                    Text {
                                        text: data.name;
                                    }

                                    clicked => {
                                        set-active-folder(data.name)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        Text {
            text: content_of_file;
        }
    }
}
