import { Button, VerticalBox, ScrollView, ListView } from "std-widgets.slint";

export component FlatFileTree {
    in property <[string]> files;
}

export enum SolItemType {
    Folder,
    File,
    Script,
    Eml,
}

export struct SolItem {
    name: string,
    item_type: SolItemType,
    active: bool,
    selected: bool,
    index: int,
    path: string,
}

export struct pos {
    x: int,
    y: int,
}

export component AppWindow inherits Window {
    in-out property <[SolItem]> files;
    in-out property <[SolItem]> child_files;
    in-out property <string> content_of_file;
    in-out property <pos> position;

    callback key_presed(string);

    width: 1000px;
    height: 500px;

    background: #383C4A;

    FocusScope {
        key-pressed(event) => {
            key_presed(event.text);
            accept
        }
        GridLayout {
            ScrollView {
                width: parent.width / 3;
                height: parent.height;
                viewport-height: parent.height;

                ListView {
                    for data in files: Rectangle {
                        GridLayout {
                            Row {
                                Rectangle {
                                    background: #3B4052;

                                    Text {
                                        text: data.name;
                                    }
                                }
                            }
                        }
                    }
                }
            }

            ScrollView {
                width: parent.width / 3;
                height: parent.height;
                viewport-width: parent.width / 3;
                viewport-height: parent.height;

                Text{
                    text: position.x;
                }

                ListView {
                    for data in child_files: Rectangle {
                        GridLayout {
                            Row {
                                Rectangle {
                                    background: data.index == position.y ? #1ECBE1 : #E1341E;

                                    Text {
                                        text: data.name;
                                    }
                                }
                            }
                        }
                    }
                }
            }

            ScrollView {
                Text {
                    text: content_of_file;
                }
            }
        }
    }
}
